apiVersion: v1
kind: ConfigMap
metadata:
  name: nam-ipam-environment-ssi-{{ .Values.settings.infrastructure }}-config
  namespace: ssi
data:
  config.yaml: |
    ---
    DENO_ENV: {{ .Values.settings.environment | quote }}
    SSI_NAME: "SSI-IPAM-NAM-NSG"
    SSI_INTERVAL: {{ .Values.settings.interval | quote }}
    REQUEST_TIMEOUT: {{ .Values.settings.timeout | quote }}
    CRON_MODE: {{ .Values.settings.continuousMode | quote }}
    NAM_URL: {{ .Values.integration.nam.url | quote }}
    IPAM_URL: {{ .Values.integration.ipam.url | quote }}
    SPLUNK_URL: {{ .Values.integration.splunk.url | quote }}
    SPLUNK_INDEX: {{ .Values.integration.splunk.index | quote }}
    SPLUNK_SOURCE: {{ .Values.integration.splunk.source | quote }}
    SPLUNK_SOURCE_TYPE: "nam-ipam-environment-ssi"
