schedule: "*/15 * * * *"

limits:
  memory:
    min: "384Mi"
    max: "1152Mi"
  cpu:
    min: "300m"
    max: "600m"

settings:
  environment: production
  infrastructure: qa
  interval: 300
  continuousMode: false

integration:
  nam:
    url: "https://qa.dcn.nhn.no:3000/api"
  ipam:
    url: "https://ipam.qa.dcn.nhn.no/api"
  splunk:
    url: "https://splunk-hec.nhn.no"
    index: "dc_nam"
    source: "nam-ipam-environment-ssi:qa"

credentials:
  namToken: "{{ .Values.credentials.namToken }}"
  splunkToken: "{{ .Values.credentials.splunkToken }}"
  ipamToken: "{{ .Values.credentials.ipamToken }}"
workspace: ssi
